In [1]:
import tensorflow as tf

In [3]:
print('Version :{0}'.format(tf.__version__))

Version :2.2.0


In [13]:
# create a constant tensor A
A=tf.constant([[4,3],
             [5,2]])

B=tf.constant([
        [7,8],
        [6,1]])

# concatenate columns
AB_concat=tf.concat(values=[A,B],axis=1)
AB_concat

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 7, 8],
       [5, 2, 6, 1]], dtype=int32)>

In [8]:
# create a Variable tensor V
V=tf.Variable(
            [[3,2],
            [4,5]])
V

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 2],
       [4, 5]], dtype=int32)>